-- -----------------------------------------------------------------------------
-- Schema initialisation for the Rayan jPOS demo environment.
-- Creates the ISO_MESSAGES table, supporting indexes, and a synonym that keeps
-- backwards compatibility with existing code paths expecting ISO_TRANSACTIONS.
-- -----------------------------------------------------------------------------
SET DEFINE OFF;

DECLARE
l_count INTEGER;
BEGIN
SELECT COUNT(*) INTO l_count FROM user_tables WHERE table_name = 'ISO_MESSAGES';
IF l_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE ISO_MESSAGES (
                ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                MTI VARCHAR2(4 CHAR) NOT NULL,
                PAN VARCHAR2(19 CHAR),
                PROCESSING_CODE VARCHAR2(6 CHAR) NOT NULL,
                AMOUNT VARCHAR2(12 CHAR),
                TRANSMISSION_DATETIME VARCHAR2(10 CHAR),
                STAN VARCHAR2(6 CHAR) NOT NULL,
                TERMINAL_ID VARCHAR2(16 CHAR),
                CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL
            )
        ]';
END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX IDX_ISO_MESSAGES_STAN ON ISO_MESSAGES (STAN)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN -- ORA-00955: name is already used by an existing object
            RAISE;
END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'CREATE INDEX IDX_ISO_MESSAGES_TERMINAL_CREATED ON ISO_MESSAGES (TERMINAL_ID, CREATED_AT)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'CREATE INDEX IDX_ISO_MESSAGES_PAN ON ISO_MESSAGES (PAN)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM ISO_TRANSACTIONS FOR ISO_MESSAGES';
END;
/

EXIT;